---

#- name: create groups
#  group: 
#    name: "{{ item }}"
#  loop:
#    - "{{ username }}"
#    - "{{ nrusername }}"
#    - docker

#- name: create non-root user
#  user: 
#    name: "{{ nrusername }}"
#    password: "{{ password | password_hash('sha512') }}"
#   groups:
#      - sudo
#      - docker 
#      - users
#    append: yes
#    shell: "{{ shell }}"
#    # only on initial user create
#    update_password: on_create

- name: Passwordless Sudo For "{{ item }}"
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  loop:
    - "{{ username }}"
    #  - "{{ nrusername }}"

# TODO: Revisit to pin versions to avoid breaking changes.
- name: Install System Updates
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Essential Packages
  apt:
    name: "{{ packages }}"
    state: latest

- name: Suppress Login Message (hushlogin)
  file:
    path: "/home/{{ item }}/.hushlogin"
    mode: 0644
    owner: "{{ item }}"
    group: "{{ item }}"
    modification_time: preserve
    access_time: preserve
    state: touch
  loop:
    # - "{{ nrusername }}"
    - "{{ username }}"