---
# import homepage configs
- name: Moving Homepage's Configurations to "/opt/homepage/config/"
  copy:
    src: "{{ item }}"
    dest: "/opt/homepage/config/"
    remote_src : true
  loop:
    - /home/bryan/repos/homepage-config/bookmarks.yaml
    - /home/bryan/repos/homepage-config/docker.yaml
    - /home/bryan/repos/homepage-config/kubernetes.yaml
    - /home/bryan/repos/homepage-config/services.yaml
    - /home/bryan/repos/homepage-config/settings.yaml
    - /home/bryan/repos/homepage-config/widgets.yaml

- name: Moving Homepage's Images to "/opt/homepage/images/"
  copy:
    src: "{{ item }}"
    dest: "/opt/homepage/images/"
    remote_src : true
  loop:
    - /home/bryan/repos/homepage-config/background_redgalaxy.png
    - /home/bryan/repos/homepage-config/icon_minerva.png

# import prometheus config
- name: Moving Prometheus's "prometheus.yml" to "/etc/prometheus/"
  copy:
    src: "/home/bryan/repos/prometheus-config/prometheus.yml"
    dest: "/etc/prometheus/"
    remote_src : true

#import minecraft config
- name: Moving Minecraft's Configurations to "/opt/minecraft/data/minecraft-config/"
  copy:
    src: "{{ item }}"
    dest: "/opt/minecraft/data/minecraft-config/"
    remote_src : true
  loop:
    - /home/bryan/repos/minecraft-config/icon_minerva_64.png
