---
- name: Import "docker-minerva" Repository
  git:
    repo: https://github.com/bryion/docker-minerva.git
    dest: /home/{{ username }}/repos/
    clone: yes
    update: yes

- name: Import "discord-music-bot" Repository
  git:
    repo: https://github.com/kawadeomkar/discord-music-bot.git
    dest: /home/{{ username }}/repo-kawade/discord-music-bot/
    clone: yes
    update: yes

- name: Create Container Directories
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/prometheus
    - /opt/grafana
    - /opt/homepage
    - /opt/uptimekuma
    - /opt/cadvisor
    - /opt/nginx/data
    - /opt/nginx/letsencrypt
    - /opt/filebrowser
    - /opt/actualbudget
    - /opt/speedtest-tracker/config
    - /opt/minecraft/data
    - /opt/minecraft/data/minecraft-config

    # drive2
    - /media/drive2/nextcloud/appdata
    - /media/drive2/nextcloud/data
    - /media/drive2/jellyfin/config
    - /media/drive2/sonarr/config
    - /media/drive2/prowlarr/config
    - /media/drive2/radarr/config
    - /media/drive2/sabnzbd/config
    # trashguides reference for file system
    - /media/drive2/data #for *arr, usenet, and torrents
    - /media/drive2/data/torrents #obsolete until qbittorent
    - /media/drive2/data/torrents/movies #obsolete until qbittorent
    - /media/drive2/data/torrents/tv #obsolete until qbittorent
    - /media/drive2/data/usenet
    - /media/drive2/data/usenet/incomplete
    - /media/drive2/data/usenet/complete
    - /media/drive2/data/usenet/complete/movies
    - /media/drive2/data/usenet/complete/tv
    - /media/drive2/data/media
    - /media/drive2/data/media/tv
    - /media/drive2/data/media/movies

    #- /opt/adguardhome/conf
    #- /opt/adguardhome/work
    - /opt/pihole/etc-pihole
    - /opt/pihole/etc-dnsmasq.d

- name: Changing Permissions of "/opt" 
  shell: chown bryan:bryan /opt

