---
- name: Import "docker-minerva" Repository
  git:
    repo: https://github.com/bryion/docker-minerva.git
    dest: /home/{{ username }}/repos/
    clone: yes
    update: yes

- name: Import "discord-music-bot" Repository
  git:
    repo: https://github.com/kawadeomkar/discord-music-bot.git
    dest: /home/{{ username }}/repo-kawade/discord-music-bot/
    clone: yes
    update: yes

- name: Create Container Directories
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/prometheus
    - /opt/grafana
    - /opt/homepage
    - /opt/uptimekuma
    - /opt/cadvisor
    - /opt/nginx/data
    - /opt/nginx/letsencrypt
    - /media/drive2/torrents
    - /media/drive2/nextcloud/appdata
    - /media/drive2/nextcloud/data
    - /media/drive2/jellyfin/config
    - /media/drive2/sonarr/config
    - /media/drive2/prowlarr/config
    - /media/drive2/radarr/config
    - /media/drive2/sabnzbd/config
    - /media/drive2/sabnzbd/incomplete
    #- /opt/adguardhome/conf
    #- /opt/adguardhome/work
    - /opt/pihole/etc-pihole
    - /opt/pihole/etc-dnsmasq.d

- name: Changing Permissions of "/opt" 
  shell: chown bryan:bryan /opt

