---
- name: Import "docker-minerva" Repository
  git:
    repo: https://github.com/bryion/docker-minerva.git
    dest: /home/{{ username }}/repos/
    clone: yes
    update: yes

- name: Create Container Directories
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/prometheus
    - /opt/grafana
    - /opt/homepage
    - /opt/uptimekuma
    - /opt/cadvisor
    - /opt/nginx/data
    - /opt/nginx/letsencrypt
    - /opt/nextcloud/appdata
    - /opt/nextcloud/data
    - /opt/jellyfin/config
    - /opt/jellyfin/tvshows
    - /opt/jellyfin/movies

- name: Changing Permissions of "/opt" 
  shell: chown bryan:bryan /opt

