---
- name: Import "docker-compose.yml"
  git:
    repo: https://github.com/bryion/docker-minerva.git
    dest: /home/bryan/repos/
    clone: yes
    update: yes


- name: Create Container Directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/homer
